### ISSUE TITLE
bump version in python

### ISSUE THREAD

**Issue by propertone** [rra/remctl#29]
The python version in setup.py and remctl.py still has `3.16` on the `3.17` release

**Comment by rra** [comment]
Ugh, sorry about that. Fixed in Git, although I probably won't make a new release just for this bug.

I'm planning on separating the Python module into a new Git repository and package with its own release schedule so that I can easily upload it to PyPI, so this issue will probably be closed once that happens.

**Comment by rra** [comment]
This should now be fixed in remctl 3.18, now released.
